export enum SOCKET_SCREEN {
  SYSTEM_IMPORT = 'SYSTEM_IMPORT',
  PROGRESS_WAITING = 'PROGRESS_WAITING',
}

export enum SOCKET_SCREEN_ACTION {
  SYSTEM_IMPORT_EXTRACT_DONE = 'SYSTEM_IMPORT_EXTRACT_DONE',
  SYSTEM_IMPORT_UPDATE_DONE = 'SYSTEM_IMPORT_UPDATE_DONE',
  SYSTEM_IMPORT_UPDATE_ERROR = 'SYSTEM_IMPORT_UPDATE_ERROR',
  PROGRESS = 'PROGRESS',
}
