export enum ORDER_STATUS {
  'DRAFT' = 'DRAFT',
  'PROCESSING' = 'PROCESSING',
  'PENDING' = 'PENDING',
  'FULFILLED' = 'FULFILLED',
  'CANCELED' = 'CANCELED',
  'DONE' = 'DONE',
}

export enum ORDER_TIME_LINE_ACTION {
  'SEND_EMAIL' = 'SEND_EMAIL',
  'ADD_TRACKING_NUMBER' = 'ADD_TRACKING_NUMBER',
}

export enum COUPON {
  'PERCENT' = 'PERCENT',
  'VALUE' = 'VALUE',
  'FREE_SHIPPING' = 'FREE_SHIPPING',
}

export enum ORDER_PAID_STATUS {
  'PAID' = 'PAID',
  'UNPAID' = 'UNPAID',
  'ABANDONED' = 'ABANDONED',
}
