export enum PUBLISH_SCOPES {
  ALL_PUBLISHERS,
  SPECIFIC_PUBLISHERS,
}

export enum DISCOUNT_TYPES {
  PERCENTAGE = 'PERCENTAGE',
  FIXED_AMOUNT = 'FIXED_AMOUNT',
  FREE_SHIPPING = 'FREE_SHIPPING',
}

export enum MINIMUM_REQUIREMENTS {
  NONE = 'NONE',
  MINIMUM_PURCHASE = 'MINIMUM_PURCHASE',
  MINIMUM_QUANTITY = 'MINIMUM_QUANTITY',
}

export enum VARIANT_DISPLAY_TYPES {
  BUTTON = 'BUTTON',
  DROPDOWN = 'DROPDOWN',
}

export enum CART_BUTTON_TYPES {
  DEFAULT = 'DEFAULT',
  WITH_TEXT = 'WITH_TEXT',
}

export enum CHECK_OUT_PAGE_TYPES {
  DEFAULT = 'DEFAULT',
  FULL_ADDRESS = 'FULL_ADDRESS',
  REDIRECT = 'REDIRECT',
}

export enum SHIPPING_RULE_TYPES {
  QUANTITY = 'QUANTITY',
  PRICE = 'PRICE',
}

export enum SHIPPING_RULE_OPERATORS {
  EQUAL = '=',
  GREATER_THAN_OR_EQUAL = '>=',
}
